import { Roboto_Mono, Mulish } from "next/font/google";
import "../styles/Global.css";
import NavBar from "@/components/NavBar";
import Provider from "@/context/Provider";
import { Metadata } from "next";

const roboto = Roboto_Mono({
  weight: ["300", "500"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

const mulish = Mulish({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "My Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${mulish.className} bg-zinc-800 min-h-screen`}>
          <header className="fixed top-0 z-20 w-full p-3 lg:p-5 bg-zinc-900">
            <NavBar />
          </header>
          {children}
        </body>
      </Provider>
    </html>
  );
}
